version: 2
jobs:
  build:

    docker:
      - image: circleci/node:10
      
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setter miljøvariable
          command: |
            echo 'export RELEASE_VERSION="$(git rev-list --count $CIRCLE_SHA1)"' >> $BASH_ENV
            echo 'export DOCKER_IMAGE_FULL_NAME="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$RELEASE_VERSION"' >> $BASH_ENV
      - run:
          name: Bygger Docker image
          command: docker build -t "$DOCKER_IMAGE_FULL_NAME" .
      - run:
          name: Pusher Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "$DOCKER_IMAGE_FULL_NAME"

      # # Download and cache dependencies
      # - restore_cache:
          # keys:
          # - v1-dependencies-{{ checksum "package.json" }}
          # # fallback to using the latest cache if no exact match is found
          # - v1-dependencies-

      # - save_cache:
          # paths:
            # - node_modules
          # key: v1-dependencies-{{ checksum "package.json" }}

